In [9]:
import numpy as np

In [10]:
#1. Write a program to create a 5 dimensional array with all zeros and ones
w=np.zeros((1,2,3,4,5),dtype=int)
print(w)
k=np.ones((1,2,3,4,5),dtype=int)
print(k)


[[[[[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]

   [[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]

   [[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]]


  [[[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]

   [[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]

   [[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]]]]
[[[[[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]

   [[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]

   [[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]]


  [[[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]

   [[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]

   [[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]]]]


In [11]:
#2.Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which
#create a new array of shape (3,10)
z= np.zeros((10),dtype=int)
k= np.ones((10),dtype=int)
m= np.full(10, 5)
print(z)
print(k)
print(m)



[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


In [12]:
#3.Write a program to create a 3x4 matrix filled with values from 10 to 21.
np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [13]:
#4. Write a program to create a 10x10 zero matrix with elements on the main diagonal equal to
#0,1,2,3,4,5,6,7,8,9,
np.diag([0,1,2,3,4,5,6,7,8,9]).reshape(10,10)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [14]:
#5.)Write a program to create a 4x4 array. Create an array from below array by swapping first and
#last, second and third columns.
l=np.arange(1,17).reshape(4,4)
k=l[::-1]
print(k)

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [15]:
#6. Write a program to reverse an array (the first element becomes the last).
#Given array:
#[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]
np.arange(27,11,-1)

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [16]:
#7.) Write a program to access all the elements greater than 30 and less than 80 and multiples of 5
#from an array of shape 10,10 .Elements range from 1 to 100
n=np.arange(1,101).reshape(10,10)
m=(n>30) &(n<80) & (n%5==0)

In [17]:
n[m]

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

In [18]:
#8.Write a program to create a 2D array with 1 on the border and 0 inside.
np.array([1,0,0,0]).reshape(2,2)

array([[1, 0],
       [0, 0]])

In [37]:
#9.Write a program to create a checkerboard pattern .Don't use default array function
#Checkerboard pattern:
#[[0 1 0 1 0 1 0 1]
#[1 0 1 0 1 0 1 0]
#[0 1 0 1 0 1 0 1]
#[1 0 1 0 1 0 1 0]
#[0 1 0 1 0 1 0 1]
#[1 0 1 0 1 0 1 0]
#[0 1 0 1 0 1 0 1]
#[1 0 1 0 1 0 1 0]]
l=[]
for i in range(0,64):
    a=i/8
    if(a%2==0):
        if(i%2==0):
            l.append(1)
        else:
            l.append(0)
    else:
        if(i%2==0):
            l.append(0)
        else:
            l.append(1)
            
x=np.array(l).reshape(8,8)
print(x)





[[1 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [1 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [1 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [1 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [20]:
#10.) Write a program to find common values between two arrays.
#Expected Output:
#array1: [10 20 40 60]
#array2: [10, 30, 40,50]
k=[10,20,40,60]
R=[10,30,40,50]
l=[]
for i in k:
    if i in R:
        l.append(i)
        print(l)
    
    


[10]
[10, 40]


In [36]:
#11.Write a program to create an array 2d array and then reshape into 1d array
k=([1,2,3,4])
l=[]
l.append(k)
n=len(l)
x=np.array(l,ndmin=2)
print(x)
print(x.reshape(-1))





[[1 2 3 4]]
[1 2 3 4]


In [45]:
#12.) Write a user defined function for creating a 1 or 2d array from scratch without using array
#functions
def n(rows, cols=None):
    if cols is None:
         array = [0] * rows
    else:
        array = [[0] * cols for _ in range(rows)]
        return array
    array_1d = n(5)


# i am not getting this code sir