In [7]:
import numpy as np

In [8]:
w=np.genfromtxt(r"C:\Users\KATYAYANI\Downloads\tipsf.csv",delimiter=",",skip_header=1)

In [9]:
w

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

In [10]:
#1.what is the total bill value
np.sum(w[:,1])

4827.77

In [11]:
#2.what is the total tip value
np.sum(w[:,2])

731.5799999999999

In [12]:
#3.count how many number os sat,sun,thu,fri are there
k=np.unique(w[:,5],return_counts=True)
m,n=k
j=0
for i in m:
    if (i==0):
        print("sunday=",n[j])
        j+=1
    elif (i==1):
        print("saturday=",n[j])
        j+=1
    elif (i==2):
        print("thursaday=",n[j])
        j+=1
    elif (i==3):
        print("friday=",n[j])
        j+=1

sunday= 87
saturday= 76
thursaday= 62
friday= 19


In [13]:
#4.how many smokers are there
np.sum(w[:,4],dtype=int)

93

In [30]:
#5.whats is the average tip given by men and women
r=np.sum(w[:,2].take(np.where(w[:,3]==0)))
k=np.sum(w[:,2].take(np.where(w[:,3]==1)))
b=np.unique(w[:,3],return_counts=True)
q,a=b
print(r/a[0],"average tip given by female")
print(k/a[1],"average tip given by male")

2.8334482758620685 average tip given by female
3.0896178343949043 average tip given by male


In [31]:
#6.how much money spent by men and women
a=np.sum(w[:,1].take(np.where(w[:,3]==0)))
b=np.sum(w[:,1].take(np.where(w[:,3]==1)))
print("total amount spent by female: ",np.round(a))
print("total amount spent by male: ",np.round(b))

total amount spent by female:  1571.0
total amount spent by male:  3257.0


In [11]:
#7.what is min and max tip given
k=np.min(w[:,2])
m=np.max(w[:,2])
print("min of tip",k)
print("max of tip",m)


min of tip 1.0
max of tip 10.0


In [1]:
#8.how many males and females are going for dinner and lunch


In [34]:
#9.find out average size
k=np.unique(w[:,7],return_counts=True)
a,b=k
avg=np.sum(w[:,7])/np.sum(b)
print("average of size = ",np.round(avg))

average of size =  3.0


In [29]:
#10.how many female and male smokers are there
k=np.unique(w[:,3].take(np.where((w[:,4]==1))),return_counts=True)
a,b=k
for i in a:
    if (i==0):
        print("female smokers are :",b[0])
    else:
        print("male smokers are :",b[1])


female smokers are : 33
male smokers are : 60


In [1]:
import numpy as np

In [2]:
w=np.genfromtxt(r"C:\Users\KATYAYANI\Downloads\train_extended.csv",delimiter=",",skip_header=1)

In [3]:
w

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

In [4]:
#1.what is the max and min length
k=np.min(w[:,0])
m=np.max(w[:,0])
print("minimum length",k)
print("maximum length",m)

minimum length 0.0
maximum length 7.58349125


In [5]:
#2.findout difference between maximum and minimum
a=np.max(w)-np.min(w)
print("difference",a)

difference 80.10151225


In [6]:
#3.find column wise average
def f1(w):
    return np.sum(w)/200000
np.apply_along_axis(f1,0,w)
    

array([ 1.31244808,  1.02032036,  0.34602787, 23.12343631,  9.98937025,
        4.99318096,  6.63422915,  9.950615  ])

In [7]:
#4.findout all the ages whose height is >0.
z=w[:,7].take(np.where(w[:,2]>0.4))
print(z.shape)
print(z)
    

(1, 55336)
[[11. 14. 13. ... 11. 11. 11.]]


In [8]:
#5.what is the average height and weight of the persons who age is 10
n=np.array(k)
age_10_n = n[n[:,2] == 10]
avg_height = np.mean(age_10_n[:,2])
avg_weight = np.mean(age_10_n[:,3])

print("Average Height for age 10:", avg_height)
print("Average Weight for age 10:", avg_weight)

#i am not getting this code sir


IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

In [9]:
#6.what is the total shell weight
np.round(np.sum(w[:,6]))

1326846.0

In [10]:
#7.how many persons belongs to each and unique age
np.unique(w[:,7],return_counts=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))

In [11]:
#8.what is difference between shucked weight and viscara weight
k=np.sum(w[:,4])-np.sum(w[:,5])
print("differnce between shucked weight and viscara weight",np.round(k))

differnce between shucked weight and viscara weight 999238.0


In [12]:
#9.what is the average height of the persons whose age between 14 &19
k=w.take(np.where((w[:,7]>14) & (w[:,7]<19)))
sum=np.sum(k)
count=list(k.shape)
print("average height of the persons age is between 14 and 19 is ",np.round(sum/count[1]))

average height of the persons age is between 14 and 19 is  7.0


In [13]:
k=np.sum(w[:,3:7])
c=list(w.shape)
print("the average weight if we included shucked weight,viscara weight,and shell weight",k)

the average weight if we included shucked weight,viscara weight,and shell weight 8948043.333077429
